---
inherit_gem:
  rubocop-fnando: .rubocop-rails.yml

AllCops:
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.0

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 500

Metrics/LineLength:
  Max: 150

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/Lambda:
  EnforcedStyle: literal

Style/LambdaCall:
  EnforcedStyle: braces

Style/MultilineBlockChain:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: aligned