version: '3.5'
services:
  db:
    container_name: social_app-db
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports: ["5432:5432"]
    expose: ["5432"]
  redis:
    image: redis
    command: redis-server
    volumes:
      - 'redis:/data'
  web:
    container_name: social_app_web
    build: .
    # command: bash -c "while [ true ]; do sleep 10; done"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/social-app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL_CACHING=redis://redis:6379/0
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password

volumes:
  redis:
  postgres: